### ISSUE TITLE
ProtoSpace挙動確認

### ISSUE THREAD

**Issue by 09200515** [09200515/protospace-34564#1]
#URL
https://protospace-34564.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **コメントを投稿すると、詳細ページに戻ってくるようにしましょう**
エラーページに遷移してしまいます
<img width="967" alt="スクリーンショット 2021-02-18 11 23 40" src="https://user-images.githubusercontent.com/62644781/108295843-c9105780-71db-11eb-8646-d94ec37b9a1b.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by 09200515** [comment]
確認ありがとうございます。

ご指摘いただいたエラーの修正を行いました。
改めてご確認よろしくお願いいたします。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by 09200515** [comment]
ご確認ありがとうございました！
